os: linux
dist: bionic
language: node_js
node_js:
  - node
install: true

addons:
  apt:
    packages:
    - fakeroot
    - rpm
    - unzip
    - zip

script:
  - electron-forge make

before_deploy:
  - echo "$TRAVIS_BUILD_NUMBER" "$TRAVIS_COMMIT"
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git tag "$TRAVIS_BUILD_NUMBER" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - ./out/make/zip/linux/x64/HyperChat-linux-x64-1.0.0.zip
    - ./out/make/deb/x64/hyperchat_1.0.0_amd64.deb
    - ./out/make/rpm/x64/HyperChat-1.0.0-1.x86_64.rpm
  on:
    repo: hypercubemc-github/HyperChat-Electron-App
  tag_name: $TRAVIS_BUILD_NUMBER
  target_commitish: $TRAVIS_COMMIT
  name: HyperFall Build $TRAVIS_BUILD_NUMBER
  edge: true

# cache:
#   directories:
#     - node_modules
#     - $HOME/.cache/electron
#     - $HOME/.cache/electron-builder
