if: tag IS blank
language: node_js
node_js:
  - node
jobs:
  include:
    - stage: Build
      os: windows
      workspaces:
        create:
          name: windows-workspace
          paths: .

      install:
        - npm install

      script:
        - npm run make

    - os: osx
      osx_image: xcode11.3
      workspaces:
        create:
          name: osx-workspace
          paths: .

      install:
        - npm install

      script:
        - npm run make

    - os: linux
      dist: bionic
      workspaces:
        create:
          name: linux-workspace
          paths: .

      addons:
        apt:
          packages:
          - fakeroot
          - rpm
          - unzip
          - zip

      install:
        - npm install

      script:
        - npm run make

    - stage: Deploy
      os: linux
      dist: bionic
      workspaces:
        use:
          - windows-workspace
          - osx-workspace
          - linux-workspace
      git:
        clone: false

      script:
        - ls -laR

      before_deploy:
        - echo "$TRAVIS_BUILD_NUMBER" "$TRAVIS_COMMIT"
        - git config --local user.name "$USER_NAME"
        - git config --local user.email "$USER_EMAIL"
        - git tag "$TRAVIS_BUILD_NUMBER" "$TRAVIS_COMMIT"

      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file:
          - ./out/make/squirrel.windows/x64/HyperChat-1.0.0-Setup.exe
          - ./out/make/squirrel.windows/x64/HyperChat-1.0.0-full.nupkg
          - ./out/make/squirrel.windows/x64/RELEASES
          - ./out/make/zip/win32/x64/HyperChat-win32-x64-1.0.0.zip
          - ./out/make/HyperChat-1.0.0.dmg
          - ./out/make/zip/darwin/x64/HyperChat-darwin-x64-1.0.0.zip
          - ./out/make/deb/x64/hyperchat_1.0.0_amd64.deb
          - ./out/make/rpm/x64/HyperChat-1.0.0-1.x86_64.rpm
          - ./out/make/zip/linux/x64/HyperChat-linux-x64-1.0.0.zip
        on:
          repo: hypercubemc-github/HyperChat-App
        tag_name: $TRAVIS_BUILD_NUMBER
        target_commitish: $TRAVIS_COMMIT
        name: HyperChat Electron App Build $TRAVIS_BUILD_NUMBER
        edge: true
